import java.awt.*;
import javax.swing.*;
public class book extends javax.swing.JFrame {

    /**
     * Creates new form book
     */
    public book() {
        initComponents();
        setTitle("Select Train");
        setLocationRelativeTo(null);
        
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        n1 = new javax.swing.JLabel();
        sd1 = new javax.swing.JLabel();
        tn1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        du1 = new javax.swing.JLabel();
        dep1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        train1 = new javax.swing.JLabel();
        train2 = new javax.swing.JLabel();
        train3 = new javax.swing.JLabel();
        train4 = new javax.swing.JLabel();
        train5 = new javax.swing.JLabel();
        train6 = new javax.swing.JLabel();
        train7 = new javax.swing.JLabel();
        train8 = new javax.swing.JLabel();
        train9 = new javax.swing.JLabel();
        train10 = new javax.swing.JLabel();
        r10 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setLayout(null);

        n1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n1.setText("No.");
        jPanel1.add(n1);
        n1.setBounds(20, 90, 70, 15);

        sd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sd1.setText("Start Destination");
        jPanel1.add(sd1);
        sd1.setBounds(70, 90, 140, 15);

        tn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tn1.setText("Train Name");
        jPanel1.add(tn1);
        tn1.setBounds(400, 90, 110, 15);

        d1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d1.setText("Destination");
        jPanel1.add(d1);
        d1.setBounds(560, 90, 110, 15);

        s1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s1.setText("Stops ");
        jPanel1.add(s1);
        s1.setBounds(940, 90, 90, 15);

        du1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        du1.setText("Duration");
        jPanel1.add(du1);
        du1.setBounds(840, 90, 100, 15);

        dep1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dep1.setText("Departs");
        jPanel1.add(dep1);
        dep1.setBounds(1010, 90, 90, 15);

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("<-- Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(1090, 570, 81, 23);

        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setText("Book");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(540, 550, 110, 30);

        L1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L1.setText("ALL Trains");
        jPanel1.add(L1);
        L1.setBounds(520, 20, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Select Train");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1100, 90, 80, 14);

        jLabel1.setText("Daily Same Trains Are Available");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 630, 190, 14);

        train1.setText("01            Howrah (HWH)                                                                                   Veraval Exp (16334)                Kalka Railway Station (KLK)                                           32 hrs 55 min            37               01:30am");
        jPanel1.add(train1);
        train1.setBounds(20, 150, 1100, 14);

        train2.setText("02            New Delhi Railway Station (NDLS)                                                KALKA SPL (02012)                Kalka Railway Station (KLK)                                           2 hrs 56 min               4                07:45am");
        jPanel1.add(train2);
        train2.setBounds(20, 190, 1100, 14);

        train3.setText("03            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           CSTM HWH SPL (02809)       Howrah (HWH)                                                                  33 hrs 15 min            41               08:00am");
        jPanel1.add(train3);
        train3.setBounds(20, 230, 1100, 14);

        train4.setText("04            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           MMCT RAJ (02172)                  New Delhi Railway Station (NDLS)                               23 hrs                         32               09:15am");
        jPanel1.add(train4);
        train4.setBounds(20, 270, 1110, 14);

        train5.setText("05            Payyanur Railway Station (PAY)                                                      Vivek Exp (22852)                    Howrah (HWH)                                                                  41 hrs 45 min            43               11:30am");
        jPanel1.add(train5);
        train5.setBounds(20, 310, 1100, 20);

        train6.setText("06            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           Paschim Exp (22926)             Kalka Railway Station (KLK)                                            28 hrs 45 min           38                12:00pm");
        jPanel1.add(train6);
        train6.setBounds(20, 360, 1100, 14);

        train7.setText("07            Kalka Railway Station (KLK)                                                            KALKA SHTBDI (12011)         New Delhi Railway Station (NDLS)                               4 hrs                             6                 16:15pm");
        jPanel1.add(train7);
        train7.setBounds(20, 400, 1100, 14);

        train8.setText("08            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           Veraval Exp (16334)                Payyanur Railway Station (PAY)                                     18 hrs 30 min             25               18:30pm");
        jPanel1.add(train8);
        train8.setBounds(20, 440, 1100, 14);

        train9.setText("09             Howrah (HWH)                                                                                  Howrah mail (12809)             Chhatrapati Shivaji Maharaj Terminus (CSTM)           33 hrs 15 min             44               20:35pm");
        jPanel1.add(train9);
        train9.setBounds(20, 480, 1100, 14);

        train10.setText("10            New Delhi Railway Station (NDLS)                                                HWH NDLS SPL (02301)      Howrah (HWH)                                                                   17 hrs 35 min             22               21:30pm");
        jPanel1.add(train10);
        train10.setBounds(20, 514, 1100, 20);

        r10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r10ActionPerformed(evt);
            }
        });
        jPanel1.add(r10);
        r10.setBounds(1130, 520, 20, 21);

        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });
        jPanel1.add(r9);
        r9.setBounds(1130, 480, 20, 21);

        r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8ActionPerformed(evt);
            }
        });
        jPanel1.add(r8);
        r8.setBounds(1130, 440, 20, 21);

        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });
        jPanel1.add(r7);
        r7.setBounds(1130, 400, 21, 23);

        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        jPanel1.add(r6);
        r6.setBounds(1130, 360, 21, 21);

        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        jPanel1.add(r5);
        r5.setBounds(1130, 310, 21, 21);

        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel1.add(r4);
        r4.setBounds(1130, 270, 20, 21);

        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel1.add(r3);
        r3.setBounds(1130, 230, 20, 21);

        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2);
        r2.setBounds(1130, 190, 20, 21);

        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(1130, 150, 21, 21);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("( Daily same trains running at same time )");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 590, 260, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shruti\\Desktop\\trackm.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-10, -20, 1220, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         new home().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       
       if(r1.isSelected()){
       new fillticket1().setVisible(true);
       this.setVisible(false);      
        }
       if(r2.isSelected()){  
       new fillticket2().setVisible(true);
       this.setVisible(false);       
      } 
       if(r3.isSelected()){  
       new fillticket3().setVisible(true);
       this.setVisible(false);       
      } 
       if(r4.isSelected()){  
       new fillticket4().setVisible(true);
       this.setVisible(false);       
      } 
       if(r5.isSelected()){  
       new fillticket5().setVisible(true);
       this.setVisible(false);       
      } 
       if(r6.isSelected()){  
       new fillticket6().setVisible(true);
       this.setVisible(false);       
      } 
       if(r7.isSelected()){  
       new fillticket7().setVisible(true);
       this.setVisible(false);       
      } 
       if(r8.isSelected()){  
       new fillticket8().setVisible(true);
       this.setVisible(false);       
      } 
       if(r9.isSelected()){  
       new fillticket9().setVisible(true);
       this.setVisible(false);       
      } 
      if(r10.isSelected()){  
       new fillticket10().setVisible(true);
       this.setVisible(false);       
      } 
      else{
     { 
         JOptionPane.showMessageDialog(null, "Please select a Train"); }
      }
     
    }//GEN-LAST:event_b1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        if (r1.isSelected());
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);            
    }//GEN-LAST:event_r1ActionPerformed

    private void r10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r10ActionPerformed
            if (r10.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
    }//GEN-LAST:event_r10ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
         if (r2.isSelected());
             r1.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);    
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
       if (r3.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
         if (r4.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
         if (r5.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r5ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
         if (r6.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r6ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
          if (r7.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r8.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r7ActionPerformed

    private void r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8ActionPerformed
             if (r8.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r9.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r8ActionPerformed

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
            if (r9.isSelected());
             r1.setSelected(false);
             r2.setSelected(false);
             r3.setSelected(false);
             r4.setSelected(false);
             r5.setSelected(false);
             r6.setSelected(false);
             r7.setSelected(false);
             r8.setSelected(false);
             r10.setSelected(false);
    }//GEN-LAST:event_r9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel dep1;
    private javax.swing.JLabel du1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel n1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel sd1;
    private javax.swing.JLabel tn1;
    private javax.swing.JLabel train1;
    private javax.swing.JLabel train10;
    private javax.swing.JLabel train2;
    private javax.swing.JLabel train3;
    private javax.swing.JLabel train4;
    private javax.swing.JLabel train5;
    private javax.swing.JLabel train6;
    private javax.swing.JLabel train7;
    private javax.swing.JLabel train8;
    private javax.swing.JLabel train9;
    // End of variables declaration//GEN-END:variables
}
