
public class Trains extends javax.swing.JFrame {

    /**
     * Creates new form Trains
     */
    public Trains() {
        initComponents();
        setTitle("Trains available");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        n1 = new javax.swing.JLabel();
        sd1 = new javax.swing.JLabel();
        tn1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        du1 = new javax.swing.JLabel();
        dep1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        train1 = new javax.swing.JLabel();
        train2 = new javax.swing.JLabel();
        train3 = new javax.swing.JLabel();
        train4 = new javax.swing.JLabel();
        train5 = new javax.swing.JLabel();
        train6 = new javax.swing.JLabel();
        train7 = new javax.swing.JLabel();
        train8 = new javax.swing.JLabel();
        train9 = new javax.swing.JLabel();
        train10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        n1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n1.setText("No.");
        jPanel1.add(n1);
        n1.setBounds(20, 90, 70, 15);

        sd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sd1.setText("Start Destination");
        jPanel1.add(sd1);
        sd1.setBounds(70, 90, 140, 15);

        tn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tn1.setText("Train Name");
        jPanel1.add(tn1);
        tn1.setBounds(400, 90, 110, 15);

        d1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d1.setText("Destination");
        jPanel1.add(d1);
        d1.setBounds(560, 90, 110, 15);

        s1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s1.setText("Stops ");
        jPanel1.add(s1);
        s1.setBounds(940, 90, 90, 15);

        du1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        du1.setText("Duration");
        jPanel1.add(du1);
        du1.setBounds(840, 90, 100, 15);

        dep1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dep1.setText("Departs");
        jPanel1.add(dep1);
        dep1.setBounds(1010, 90, 90, 15);

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("<-- Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(1000, 570, 81, 23);

        L1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L1.setText("ALL Trains");
        jPanel1.add(L1);
        L1.setBounds(520, 20, 140, 40);

        jLabel1.setText("Daily Same Trains Are Available");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 630, 190, 14);

        train1.setBackground(new java.awt.Color(255, 255, 255));
        train1.setText("01            Howrah (HWH)                                                                                   Veraval Exp (16334)                Kalka Railway Station (KLK)                                           32 hrs 55 min            37               01:30am");
        jPanel1.add(train1);
        train1.setBounds(20, 150, 1100, 14);

        train2.setBackground(new java.awt.Color(255, 255, 255));
        train2.setText("02            New Delhi Railway Station (NDLS)                                                KALKA SPL (02012)                Kalka Railway Station (KLK)                                           2 hrs 56 min               4                07:45am");
        jPanel1.add(train2);
        train2.setBounds(20, 190, 1100, 14);

        train3.setBackground(new java.awt.Color(255, 255, 255));
        train3.setText("03            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           CSTM HWH SPL (02809)       Howrah (HWH)                                                                  33 hrs 15 min            41               08:00am");
        jPanel1.add(train3);
        train3.setBounds(20, 230, 1100, 14);

        train4.setBackground(new java.awt.Color(255, 255, 255));
        train4.setText("04            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           MMCT RAJ (02172)                  New Delhi Railway Station (NDLS)                               23 hrs                         32               09:15am");
        jPanel1.add(train4);
        train4.setBounds(20, 270, 1110, 14);

        train5.setBackground(new java.awt.Color(255, 255, 255));
        train5.setText("05            Payyanur Railway Station (PAY)                                                      Vivek Exp (22852)                    Howrah (HWH)                                                                  41 hrs 45 min            43               11:30am");
        jPanel1.add(train5);
        train5.setBounds(20, 310, 1100, 20);

        train6.setBackground(new java.awt.Color(255, 255, 255));
        train6.setText("06            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           Paschim Exp (22926)             Kalka Railway Station (KLK)                                            28 hrs 45 min           38                12:00pm");
        jPanel1.add(train6);
        train6.setBounds(20, 360, 1100, 14);

        train7.setBackground(new java.awt.Color(255, 255, 255));
        train7.setText("07            Kalka Railway Station (KLK)                                                            KALKA SHTBDI (12011)         New Delhi Railway Station (NDLS)                               4 hrs                             6                 16:15pm");
        jPanel1.add(train7);
        train7.setBounds(20, 400, 1100, 14);

        train8.setBackground(new java.awt.Color(255, 255, 255));
        train8.setText("08            Chhatrapati Shivaji Maharaj Terminus (CSTM)                           Veraval Exp (16334)                Payyanur Railway Station (PAY)                                     18 hrs 30 min             25               18:30pm");
        jPanel1.add(train8);
        train8.setBounds(20, 440, 1100, 14);

        train9.setBackground(new java.awt.Color(255, 255, 255));
        train9.setText("09             Howrah (HWH)                                                                                  Howrah mail (12809)             Chhatrapati Shivaji Maharaj Terminus (CSTM)           33 hrs 15 min             44               20:35pm");
        jPanel1.add(train9);
        train9.setBounds(20, 480, 1100, 14);

        train10.setBackground(new java.awt.Color(255, 255, 255));
        train10.setText("10            New Delhi Railway Station (NDLS)                                                HWH NDLS SPL (02301)      Howrah (HWH)                                                                   17 hrs 35 min             22               21:30pm");
        jPanel1.add(train10);
        train10.setBounds(20, 514, 1100, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("( Daily same trains running at same time )");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 560, 260, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shruti\\Desktop\\trackm.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -40, 1680, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel dep1;
    private javax.swing.JLabel du1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel sd1;
    private javax.swing.JLabel tn1;
    private javax.swing.JLabel train1;
    private javax.swing.JLabel train10;
    private javax.swing.JLabel train2;
    private javax.swing.JLabel train3;
    private javax.swing.JLabel train4;
    private javax.swing.JLabel train5;
    private javax.swing.JLabel train6;
    private javax.swing.JLabel train7;
    private javax.swing.JLabel train8;
    private javax.swing.JLabel train9;
    // End of variables declaration//GEN-END:variables
}
